import { useEffect, useRef, useState } from 'react'
import { getLocalDate } from '../lib/dateUtils'
import {
  FEED_ACCENT_COLORS,
  FEED_LABELS,
  FEED_SEARCHING_LABELS,
  FEED_TYPES,
  fetchDigest,
  formatDigestTime,
  getNewsDigestErrorMessage,
  runNewsDigest,
} from '../lib/newsDigest'

const EMPTY_FEED_STATE = { digest: null, loading: true, generating: false, error: '' }

export default function Digest() {
  const [activeTab, setActiveTab] = useState('global')
  const [feeds, setFeeds] = useState(() =>
    Object.fromEntries(FEED_TYPES.map(feedType => [feedType, EMPTY_FEED_STATE])),
  )
  const today = useRef(getLocalDate()).current
  const hasStartedLoad = useRef(false)

  useEffect(() => {
    // Guards against React 18 StrictMode's dev-only double-invoke of this
    // effect, which would otherwise fire loadFeed() twice per feed on mount
    // and burn 2x the shared Gemini quota on every local dev page load.
    if (hasStartedLoad.current) return
    hasStartedLoad.current = true
    FEED_TYPES.forEach(feedType => loadFeed(feedType))
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  async function loadFeed(feedType) {
    setFeeds(prev => ({ ...prev, [feedType]: { ...prev[feedType], loading: true, error: '' } }))

    try {
      const cached = await fetchDigest(feedType, today)
      if (cached) {
        setFeeds(prev => ({ ...prev, [feedType]: { digest: cached, loading: false, generating: false, error: '' } }))
        return
      }
      await generateFeed(feedType)
    } catch (error) {
      setFeeds(prev => ({
        ...prev,
        [feedType]: { ...prev[feedType], loading: false, generating: false, error: getNewsDigestErrorMessage(error) },
      }))
    }
  }

  async function generateFeed(feedType) {
    setFeeds(prev => ({ ...prev, [feedType]: { ...prev[feedType], loading: false, generating: true, error: '' } }))

    try {
      const digest = await runNewsDigest({ feedType, generatedDate: today })
      setFeeds(prev => ({ ...prev, [feedType]: { digest, loading: false, generating: false, error: '' } }))
    } catch (error) {
      setFeeds(prev => ({
        ...prev,
        [feedType]: { ...prev[feedType], loading: false, generating: false, error: getNewsDigestErrorMessage(error) },
      }))
    }
  }

  const activeFeed = feeds[activeTab]

  return (
    <main className="max-w-[900px] mx-auto px-6 py-8">
      <div className="habit-card rounded-xl p-5">
        <h1 className="font-display text-3xl font-semibold text-os-fg">Digest</h1>
        <p className="mt-1 text-sm text-os-muted">Daily summaries generated by Gemini with live web search.</p>

        <div className="mt-5 flex gap-2 overflow-x-auto scroll-hide">
          {FEED_TYPES.map(feedType => (
            <button
              key={feedType}
              type="button"
              onClick={() => setActiveTab(feedType)}
              className={`rounded-lg px-3 py-2 text-sm font-body transition ${
                activeTab === feedType ? 'bg-indigo-500/15 text-os-fg' : 'text-os-muted hover:bg-indigo-500/10'
              }`}
            >
              {FEED_LABELS[feedType]}
            </button>
          ))}
        </div>
      </div>

      <div className="mt-5">
        <FeedPanel
          feedType={activeTab}
          state={activeFeed}
          onRefresh={() => generateFeed(activeTab)}
        />
      </div>
    </main>
  )
}

function FeedPanel({ feedType, state, onRefresh }) {
  const { digest, loading, generating, error } = state
  const accent = FEED_ACCENT_COLORS[feedType]
  const busy = loading || generating

  return (
    <section className="habit-card rounded-xl p-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2 text-sm text-os-muted">
          {digest?.created_at ? (
            <span>Last updated {formatDigestTime(digest.created_at)}</span>
          ) : (
            <span>Not yet generated today</span>
          )}
        </div>
        <button
          type="button"
          onClick={onRefresh}
          disabled={busy}
          className="action-pill-btn action-pill-amber"
        >
          <i className={`ti ti-${busy ? 'loader-2 animate-spin' : 'refresh'}`} />
          {generating ? 'Refreshing...' : 'Refresh'}
        </button>
      </div>

      {error && (
        <div
          className="mt-4 rounded-lg px-4 py-3 text-sm font-body"
          style={{ backgroundColor: '#EF44441f', border: '1px solid #EF444450', color: '#EF4444' }}
        >
          {error}
        </div>
      )}

      {generating && (
        <div className="mt-6 flex flex-col items-center justify-center gap-3 py-10 text-center text-os-muted">
          <i className="ti ti-world-search text-4xl animate-pulse" style={{ color: accent }} />
          <p className="text-sm">{FEED_SEARCHING_LABELS[feedType]}</p>
          <p className="text-xs">This can take 15-30 seconds.</p>
        </div>
      )}

      {loading && !generating && (
        <div className="mt-6 flex flex-col items-center justify-center gap-3 py-10 text-os-muted">
          <i className="ti ti-loader-2 text-3xl animate-spin" />
        </div>
      )}

      {!busy && !error && !digest && (
        <div className="mt-6 flex flex-col items-center justify-center gap-3 py-10 text-center text-os-muted">
          <i className="ti ti-news text-4xl" />
          <p className="text-sm">No digest yet. It will generate automatically, or hit Refresh.</p>
        </div>
      )}

      {!busy && digest?.content?.stories?.length > 0 && (
        <div className="mt-5 flex flex-col gap-3">
          {digest.content.stories.map((story, index) => (
            <StoryCard key={`${story.headline}-${index}`} story={story} accent={accent} />
          ))}
        </div>
      )}

      {!busy && !error && digest && digest.content?.stories?.length === 0 && (
        <div className="mt-6 flex flex-col items-center justify-center gap-3 py-10 text-center text-os-muted">
          <i className="ti ti-mood-empty text-4xl" />
          <p className="text-sm">No stories came back for today's search.</p>
        </div>
      )}
    </section>
  )
}

function StoryCard({ story, accent }) {
  return (
    <article className="relative overflow-hidden rounded-lg p-4" style={{ border: '1px solid var(--drawer-card-border)', background: 'var(--drawer-card-bg)' }}>
      <div className="absolute left-0 top-0 h-full w-[3px]" style={{ backgroundColor: accent }} />
      <h3 className="font-display text-base font-semibold text-os-fg">{story.headline}</h3>
      {story.summary && <p className="mt-2 text-sm leading-6 text-os-secondary">{story.summary}</p>}
      {story.source_hint && (
        <p className="mt-2 text-xs uppercase tracking-wide text-os-muted">{story.source_hint}</p>
      )}
    </article>
  )
}
