import { useEffect, useRef, useState } from 'react'
import { getLocalDate, getWeekBounds } from '../lib/dateUtils'
import {
  MIN_LOGGED_DAYS_FOR_REVIEW,
  countLoggedDaysInWeek,
  fetchReview,
  formatReviewTime,
  formatWeekRange,
  getWeeklyReviewErrorMessage,
  runWeeklyReview,
} from '../lib/weeklyReview'
import StreakDisplay from '../components/StreakDisplay'

const HABIT_COLORS = { gym: '#6366F1', japanese: '#8B5CF6', dsa: '#06B6D4' }

export default function Review() {
  const today = useRef(getLocalDate()).current
  const weekStartDate = useRef(getWeekBounds(today).mondayStr).current
  const [state, setState] = useState({
    phase: 'checking', // checking | insufficient | loading | generating | ready | error
    review: null,
    error: '',
  })
  const hasStartedLoad = useRef(false)

  useEffect(() => {
    // Guards against React 18 StrictMode's dev-only double-invoke of this
    // effect, matching the fix already applied to Digest.jsx — without it a
    // fresh /review load would fire two Gemini calls instead of one.
    if (hasStartedLoad.current) return
    hasStartedLoad.current = true
    load()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  async function load() {
    setState(prev => ({ ...prev, phase: 'checking', error: '' }))
    try {
      const cached = await fetchReview(weekStartDate)
      if (cached) {
        setState({ phase: 'ready', review: cached, error: '' })
        return
      }

      const loggedDays = await countLoggedDaysInWeek(weekStartDate, today)
      if (loggedDays < MIN_LOGGED_DAYS_FOR_REVIEW) {
        setState({ phase: 'insufficient', review: null, error: '' })
        return
      }

      await generate()
    } catch (error) {
      setState({ phase: 'error', review: null, error: getWeeklyReviewErrorMessage(error) })
    }
  }

  async function generate() {
    setState(prev => ({ ...prev, phase: 'generating', error: '' }))
    try {
      const review = await runWeeklyReview({ weekStartDate, today })
      setState({ phase: 'ready', review, error: '' })
    } catch (error) {
      setState(prev => ({ ...prev, phase: 'error', error: getWeeklyReviewErrorMessage(error) }))
    }
  }

  const { phase, review, error } = state
  const busy = phase === 'checking' || phase === 'loading' || phase === 'generating'

  return (
    <main className="max-w-[900px] mx-auto px-6 py-8">
      <div className="habit-card rounded-xl p-5">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <h1 className="font-display text-3xl font-semibold text-os-fg">Review</h1>
            <p className="mt-1 text-sm text-os-muted">
              Week of {formatWeekRange(weekStartDate)} - generated by Gemini from your own habit and goal data.
            </p>
          </div>
          {phase === 'ready' && (
            <div className="flex items-center gap-3">
              {review?.created_at && (
                <span className="text-sm text-os-muted">Last updated {formatReviewTime(review.created_at)}</span>
              )}
              <button
                type="button"
                onClick={generate}
                disabled={busy}
                className="action-pill-btn action-pill-amber"
              >
                <i className={`ti ti-${phase === 'generating' ? 'loader-2 animate-spin' : 'refresh'}`} />
                {phase === 'generating' ? 'Regenerating...' : 'Regenerate'}
              </button>
            </div>
          )}
        </div>
      </div>

      <div className="mt-5">
        {phase === 'checking' && (
          <div className="habit-card rounded-xl p-5 flex flex-col items-center justify-center gap-3 py-14 text-os-muted">
            <i className="ti ti-loader-2 text-3xl animate-spin" />
          </div>
        )}

        {phase === 'insufficient' && (
          <div className="habit-card rounded-xl p-5 flex flex-col items-center justify-center gap-3 py-14 text-center text-os-muted">
            <i className="ti ti-chart-bar text-4xl" />
            <p className="text-sm max-w-sm">
              Not enough logged days yet this week for a meaningful review. Come back after logging a few more days.
            </p>
          </div>
        )}

        {phase === 'generating' && (
          <div className="habit-card rounded-xl p-5 flex flex-col items-center justify-center gap-3 py-14 text-center text-os-muted">
            <i className="ti ti-report-analytics text-4xl animate-pulse" style={{ color: '#8B5CF6' }} />
            <p className="text-sm">Reviewing your week...</p>
            <p className="text-xs">This can take 15-30 seconds.</p>
          </div>
        )}

        {phase === 'error' && (
          <div
            className="rounded-lg px-4 py-3 text-sm font-body"
            style={{ backgroundColor: '#EF44441f', border: '1px solid #EF444450', color: '#EF4444' }}
          >
            {error}
          </div>
        )}

        {phase === 'ready' && review && <ReviewContent content={review.content} />}
      </div>
    </main>
  )
}

function ReviewContent({ content }) {
  const { summary, wins = [], slips = [], next_week_priorities: priorities = [], stats, goals = [] } = content ?? {}

  return (
    <div className="flex flex-col gap-5">
      <section className="habit-card rounded-xl p-5">
        <p className="text-[11px] font-body font-semibold uppercase tracking-widest text-os-muted">Summary</p>
        <p className="mt-2 text-sm leading-6 text-os-secondary">{summary}</p>
      </section>

      {stats && <StatsPanel stats={stats} />}

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
        <ListSection title="Wins" icon="check" color="#10B981" items={wins} />
        <ListSection title="Slips" icon="x" color="#F43F5E" items={slips} />
      </div>

      <ListSection title="Next week priorities" icon="arrow-right" color="#F59E0B" items={priorities} />

      {goals.length > 0 && <GoalsPanel goals={goals} />}
    </div>
  )
}

function ListSection({ title, icon, color, items }) {
  return (
    <section className="habit-card rounded-xl p-5">
      <p className="text-[11px] font-body font-semibold uppercase tracking-widest text-os-muted">{title}</p>
      {items.length === 0 ? (
        <p className="mt-2 text-sm text-os-muted">Nothing to report.</p>
      ) : (
        <ul className="mt-3 flex flex-col gap-2">
          {items.map((item, index) => (
            <li key={index} className="flex items-start gap-2 text-sm leading-6 text-os-secondary">
              <i className={`ti ti-${icon} mt-1 shrink-0 text-xs`} style={{ color }} />
              <span>{item}</span>
            </li>
          ))}
        </ul>
      )}
    </section>
  )
}

function StatsPanel({ stats }) {
  return (
    <section className="habit-card rounded-xl p-5">
      <div className="flex items-center justify-between">
        <p className="text-[11px] font-body font-semibold uppercase tracking-widest text-os-muted">
          Habit performance
        </p>
        <div className="flex items-center gap-2">
          <span className="text-xs text-os-muted">Overall streak</span>
          <StreakDisplay count={stats.overall_streak ?? 0} />
        </div>
      </div>

      <div className="mt-4 grid grid-cols-1 sm:grid-cols-3 gap-3">
        <StatCard color={HABIT_COLORS.gym} label="Gym" icon="barbell">
          <StatRow label="Workouts" value={stats.gym?.workouts ?? 0} />
          <StatRow label="Rest days" value={stats.gym?.rest_days ?? 0} />
          <StatRow label="Missed" value={stats.gym?.missed ?? 0} />
        </StatCard>

        <StatCard color={HABIT_COLORS.japanese} label="Japanese" icon="language">
          <StatRow label="Completion" value={`${Math.round((stats.japanese?.completion_rate ?? 0) * 100)}%`} />
          <StatRow label="Anki streak" value={stats.japanese?.subtask_streaks?.anki ?? 0} />
          <StatRow label="Duolingo streak" value={stats.japanese?.subtask_streaks?.duolingo ?? 0} />
        </StatCard>

        <StatCard color={HABIT_COLORS.dsa} label="DSA" icon="code">
          <StatRow label="Easy / Med / Hard" value={`${stats.dsa?.easy ?? 0} / ${stats.dsa?.med ?? 0} / ${stats.dsa?.hard ?? 0}`} />
          <StatRow label="Days logged" value={`${stats.dsa?.days_logged ?? 0} / ${stats.days_elapsed ?? 0}`} />
        </StatCard>
      </div>
    </section>
  )
}

function StatCard({ color, label, icon, children }) {
  return (
    <div className="relative overflow-hidden rounded-lg p-4" style={{ border: '1px solid var(--drawer-card-border)', background: 'var(--drawer-card-bg)' }}>
      <div className="absolute left-0 top-0 h-full w-[3px]" style={{ backgroundColor: color }} />
      <div className="flex items-center gap-2">
        <i className={`ti ti-${icon}`} style={{ color }} />
        <span className="font-display text-sm font-semibold text-os-fg">{label}</span>
      </div>
      <div className="mt-2 flex flex-col gap-1">{children}</div>
    </div>
  )
}

function StatRow({ label, value }) {
  return (
    <div className="flex items-center justify-between text-xs">
      <span className="text-os-muted">{label}</span>
      <span className="font-mono text-os-fg">{value}</span>
    </div>
  )
}

const GOAL_STATUS_LABELS = {
  moved_forward: 'Moved forward',
  stalled: 'Stalled',
  regressed: 'Regressed',
  new: 'No comparison yet',
}

const GOAL_STATUS_COLORS = {
  moved_forward: '#10B981',
  stalled: '#F59E0B',
  regressed: '#F43F5E',
  new: 'var(--os-muted)',
}

function GoalsPanel({ goals }) {
  return (
    <section className="habit-card rounded-xl p-5">
      <p className="text-[11px] font-body font-semibold uppercase tracking-widest text-os-muted">Goal progress</p>
      <div className="mt-3 flex flex-col gap-3">
        {goals.map(goal => (
          <div key={goal.id} className="flex flex-wrap items-center gap-x-3 gap-y-1.5">
            <div className="min-w-0 flex-1 basis-40">
              <p className="truncate text-sm text-os-fg">{goal.name}</p>
              <div className="progress-track mt-1.5 h-1.5 overflow-hidden rounded-full">
                <div
                  className="h-full rounded-full"
                  style={{ width: `${goal.progress_pct}%`, backgroundColor: GOAL_STATUS_COLORS[goal.status] }}
                />
              </div>
            </div>
            <span className="shrink-0 font-mono text-xs text-os-muted">{goal.progress_pct}%</span>
            <span
              className="shrink-0 rounded-full px-2 py-0.5 text-[11px] font-body font-semibold uppercase tracking-wide"
              style={{ backgroundColor: `${GOAL_STATUS_COLORS[goal.status]}22`, color: GOAL_STATUS_COLORS[goal.status] }}
            >
              {GOAL_STATUS_LABELS[goal.status]}
            </span>
          </div>
        ))}
      </div>
    </section>
  )
}
